//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBookCase1.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookRent
    {
        public int RentID { get; set; }
        public int UserID { get; set; }
        public int BookID { get; set; }
        public int MemberID { get; set; }
        public System.DateTime RentDate { get; set; }
        public System.DateTime ReturnDate { get; set; }
        public bool IsReturn { get; set; }
        public int RentDay { get; set; }
    
        public virtual BookArchive BookArchive { get; set; }
        public virtual MemberInformation MemberInformation { get; set; }
        public virtual UserInformation UserInformation { get; set; }
    }
}
