//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartBookCase1.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SmartBookcaseDtbsEntities13 : DbContext
    {
        public SmartBookcaseDtbsEntities13()
            : base("name=SmartBookcaseDtbsEntities13")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BookArchive> BookArchive { get; set; }
        public virtual DbSet<BookRent> BookRent { get; set; }
        public virtual DbSet<MemberInformation> MemberInformation { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserInformation> UserInformation { get; set; }
    }
}
